<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Champion;

class ChampionSeeder extends Seeder
{
    public function run(): void
    {
        $champions = [
            // Top (Baron Lane)
            ['name' => 'Aatrox', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Aatrox.png'],
            ['name' => 'Camille', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Camille.png'],
            ['name' => 'Darius', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Darius.png'],
            ['name' => 'Fiora', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fiora.png'],
            ['name' => 'Garen', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Garen.png'],
            ['name' => 'Irelia', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Irelia.png'],
            ['name' => 'Jax', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jax.png'],
            ['name' => 'Jayce', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jayce.png'],
            ['name' => 'Malphite', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Malphite.png'],
            ['name' => 'Nasus', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nasus.png'],
            ['name' => 'Renekton', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Renekton.png'],
            ['name' => 'Riven', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Riven.png'],
            ['name' => 'Sett', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sett.png'],
            ['name' => 'Shen', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Shen.png'],
            ['name' => 'Sion', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sion.png'],
            ['name' => 'Teemo', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Teemo.png'],
            ['name' => 'Tryndamere', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Tryndamere.png'],
            ['name' => 'Wukong', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MonkeyKing.png'],
            
            // Jungle
            ['name' => 'Amumu', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Amumu.png'],
            ['name' => 'Diana', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Diana.png'],
            ['name' => 'Ekko', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ekko.png'],
            ['name' => 'Evelynn', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Evelynn.png'],
            ['name' => 'Gragas', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gragas.png'],
            ['name' => 'Graves', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Graves.png'],
            ['name' => 'Hecarim', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Hecarim.png'],
            ['name' => 'Jarvan IV', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/JarvanIV.png'],
            ['name' => 'KhaZix', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Khazix.png'],
            ['name' => 'Lee Sin', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/LeeSin.png'],
            ['name' => 'Master Yi', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MasterYi.png'],
            ['name' => 'Nautilus', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nautilus.png'],
            ['name' => 'Nunu & Willump', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nunu.png'],
            ['name' => 'Olaf', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Olaf.png'],
            ['name' => 'Pantheon', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Pantheon.png'],
            ['name' => 'Rammus', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rammus.png'],
            ['name' => 'Rengar', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rengar.png'],
            ['name' => 'Shyvana', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Shyvana.png'],
            ['name' => 'Vi', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vi.png'],
            ['name' => 'Viego', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Viego.png'],
            ['name' => 'Volibear', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Volibear.png'],
            ['name' => 'Xin Zhao', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/XinZhao.png'],
            
            // Mid
            ['name' => 'Ahri', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ahri.png'],
            ['name' => 'Akali', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Akali.png'],
            ['name' => 'Akshan', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Akshan.png'],
            ['name' => 'Annie', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Annie.png'],
            ['name' => 'Aurelion Sol', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/AurelionSol.png'],
            ['name' => 'Brand', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Brand.png'],
            ['name' => 'Corki', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Corki.png'],
            ['name' => 'Fizz', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fizz.png'],
            ['name' => 'Galio', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Galio.png'],
            ['name' => 'Kassadin', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kassadin.png'],
            ['name' => 'Katarina', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Katarina.png'],
            ['name' => 'Lucian', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lucian.png'],
            ['name' => 'Orianna', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Orianna.png'],
            ['name' => 'Syndra', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Syndra.png'],
            ['name' => 'Talon', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Talon.png'],
            ['name' => 'Twisted Fate', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/TwistedFate.png'],
            ['name' => 'Veigar', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Veigar.png'],
            ['name' => 'Vladimir', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vladimir.png'],
            ['name' => 'Yasuo', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yasuo.png'],
            ['name' => 'Yone', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yone.png'],
            ['name' => 'Zed', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zed.png'],
            ['name' => 'Ziggs', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ziggs.png'],
            ['name' => 'Zoe', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zoe.png'],
            
            // ADC (Dragon Lane)
            ['name' => 'Ashe', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ashe.png'],
            ['name' => 'Caitlyn', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Caitlyn.png'],
            ['name' => 'Draven', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Draven.png'],
            ['name' => 'Ezreal', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ezreal.png'],
            ['name' => 'Jhin', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jhin.png'],
            ['name' => 'Jinx', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Jinx.png'],
            ['name' => 'KaiSa', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kaisa.png'],
            ['name' => 'Miss Fortune', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/MissFortune.png'],
            ['name' => 'Samira', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Samira.png'],
            ['name' => 'Sivir', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sivir.png'],
            ['name' => 'Tristana', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Tristana.png'],
            ['name' => 'Varus', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Varus.png'],
            ['name' => 'Vayne', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vayne.png'],
            ['name' => 'Xayah', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Xayah.png'],
            ['name' => 'Zeri', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zeri.png'],

            // Support
            ['name' => 'Alistar', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Alistar.png'],
            ['name' => 'Braum', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Braum.png'],
            ['name' => 'Janna', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Janna.png'],
            ['name' => 'Karma', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Karma.png'],
            ['name' => 'Leona', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Leona.png'],
            ['name' => 'Lulu', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lulu.png'],
            ['name' => 'Morgana', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Morgana.png'],
            ['name' => 'Nami', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nami.png'],
            ['name' => 'Pyke', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Pyke.png'],
            ['name' => 'Rakan', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rakan.png'],
            ['name' => 'Senna', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Senna.png'],
            ['name' => 'Seraphine', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Seraphine.png'],
            ['name' => 'Sona', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Sona.png'],
            ['name' => 'Soraka', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Soraka.png'],
            ['name' => 'Thresh', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Thresh.png'],
            ['name' => 'Yuumi', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Yuumi.png'],
            // More Champions
            ['name' => 'Dr. Mundo', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/DrMundo.png'],
            ['name' => 'Gwen', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gwen.png'],
            ['name' => 'Kayle', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kayle.png'],
            ['name' => 'Kayn', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kayn.png'],
            ['name' => 'Kennen', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kennen.png'],
            ['name' => 'Kindred', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kindred.png'],
            ['name' => 'Lillia', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lillia.png'],
            ['name' => 'Lux', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lux.png'],
            ['name' => 'Nilah', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nilah.png'],
            ['name' => 'Ornn', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ornn.png'],
            ['name' => 'Singed', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Singed.png'],
            ['name' => 'Swain', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Swain.png'],
            ['name' => 'Twitch', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Twitch.png'],
            ['name' => 'Urgot', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Urgot.png'],
            ['name' => 'Vex', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Vex.png'],
            ['name' => 'Warwick', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Warwick.png'],
            ['name' => 'Zyra', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zyra.png'],
            // Latest additions
            ['name' => 'Ambessa', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ambessa.png'],
            ['name' => 'Aurora', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Aurora.png'],
            ['name' => 'Bardo', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Bard.png'],
            ['name' => 'Blitzcrank', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Blitzcrank.png'],
            ['name' => 'Fiddlesticks', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Fiddlesticks.png'],
            ['name' => 'Gnar', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Gnar.png'],
            ['name' => 'Heimerdinger', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Heimerdinger.png'],
            ['name' => 'Kalista', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Kalista.png'],
            ['name' => "Kog'Maw", 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/KogMaw.png'],
            ['name' => 'Lissandra', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Lissandra.png'],
            ['name' => 'Maokai', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Maokai.png'],
            ['name' => 'Mel', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Mel.png'],
            ['name' => 'Milio', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Milio.png'],
            ['name' => 'Mordekaiser', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Mordekaiser.png'],
            ['name' => 'Nidalee', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nidalee.png'],
            ['name' => 'Nocturne', 'role' => 'Jungle', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Nocturne.png'],
            ['name' => 'Norra', 'role' => 'Support', 'image_url' => 'https://static.wikia.nocookie.net/leagueoflegends/images/0/07/NorraSquare.png'],
            ['name' => 'Poppy', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Poppy.png'],
            ['name' => 'Rell', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rell.png'],
            ['name' => 'Rumble', 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Rumble.png'],
            ['name' => 'Ryze', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Ryze.png'],
            ['name' => 'Smolder', 'role' => 'ADC', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Smolder.png'],
            ['name' => 'Taliyah', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Taliyah.png'],
            ['name' => "Vel'Koz", 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Velkoz.png'],
            ['name' => 'Viktor', 'role' => 'Mid', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Viktor.png'],
            ['name' => 'Zilean', 'role' => 'Support', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/Zilean.png'],
            ['name' => "K'Sante", 'role' => 'Top', 'image_url' => 'https://ddragon.leagueoflegends.com/cdn/16.11.1/img/champion/KSante.png'],
        ];

        foreach ($champions as $champ) {
            Champion::firstOrCreate(['name' => $champ['name']], $champ);
        }
    }
}
